efcoreApp/Controllers/KursKayitController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class KursKayitController:Controller
    {

        private readonly DataContext _context;
        public KursKayitController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var kursKayitlari = await _context
                                .KursKayitlari
                                .Include(x => x.Ogrenci)
                                .Include(x => x.Kurs)
                                .ToListAsync();
            return View(kursKayitlari);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Ogrenciler = new SelectList(await _context.Ogrenciler.ToListAsync(),"OgrenciId", "AdSoyad");
            ViewBag.Kurslar = new SelectList(await _context.Kurslar.ToListAsync(),"KursId", "Baslik");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(KursKayit model)
        {
            model.KayitTarihi = DateTime.Now;
            _context.KursKayitlari.Add(model);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }


    }
}

efcoreApp/Views/KursKayit/Create.cshtml
@model KursKayit

<h2>Kurs Kayıt Ekleme</h2>
<hr>

<form asp-controller="KursKayit" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciId" class="form-label">Öğrenci</label>
        <select asp-for="OgrenciId" asp-items="ViewBag.Ogrenciler" class="form-select">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="KursId" class="form-label">Kurs</label>
        <select asp-for="KursId" asp-items="ViewBag.Kurslar" class="form-select">
            <option value="">Seçiniz</option>
        </select>
    </div>
    

    <button type="submit" class="btn btn-secondary">Kaydet</button>
</form>

efcoreApp/Views/KursKayit/Index.cshtml
@model IEnumerable<KursKayit>

<h2>Kayıt Listesi</h2>
<a asp-action="Create" class="btn btn-primary">Kayıt Ekle</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.KayitId)</th>
            <th>@Html.DisplayNameFor(m => m.Ogrenci.OgrenciAd)</th>
            <th>@Html.DisplayNameFor(m => m.Kurs.Baslik)</th>
            <th style="width: 150px;"></th>

        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model){
            <tr>
                <td>@Html.DisplayFor(modelItem => item.KayitId)</td>
                <td>@Html.DisplayFor(modelItem => item.Ogrenci.OgrenciAd)</td>
                <td>@Html.DisplayFor(modelItem => item.Kurs.Baslik)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.OgrenciId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.OgrenciId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>