MeetingApp/Models/MeetingInfo.cs
namespace MeetingApp.Models
{
    public class MeetingInfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }  
        public int NumberOfPeople { get; set; }
        
    }

}

MeetingApp/Models/Repository.cs
namespace MeetingApp.Models
{
    public static class Repository
    {
        public static List<UserInfo> _users = new();

        static Repository()
        {
           _users.Add(new UserInfo(){Id=1,Name="Ali",Email="abc@gmail.com",Phone="1111",WillAttend=true});
           _users.Add(new UserInfo(){Id=2,Name="Hasan",Email="abc2@gmail.com",Phone="1111",WillAttend=true});
           _users.Add(new UserInfo(){Id=3,Name="Ayhan",Email="abc3@gmail.com",Phone="1111",WillAttend=false});
           
        }

        public static List<UserInfo> Users{
            get{
                return _users;
            }
        }

        public static void CreateUser(UserInfo user)
        {
            user.Id = Users.Count +1;
            _users.Add(user);
        }

        public static UserInfo? GetById(int id)
        {
            return _users.FirstOrDefault(user => user.Id ==id);
        }
    }
}

MeetingApp/Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{
    public class UserInfo
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="You must fill the Name field")]
        public string? Name { get; set; } //null
        
        [Required(ErrorMessage ="You must fill the Phone field")]
        public string? Phone { get; set; }

        [Required(ErrorMessage ="You must fill the Email Address field")]
        [EmailAddress(ErrorMessage ="You must give a valid E-Mail address")]
        public string? Email { get; set; }

        [Required(ErrorMessage ="You must select an Attend State")]
        public bool? WillAttend{ get; set; } // true, false, null       //default of bool is --> false
    }
}

MeetingApp/Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController: Controller
    {
        public IActionResult Index() //IActionResult --> View()'ı karşılar
        {
            // Gets the hour of right now
            int saat = DateTime.Now.Hour;

            //THIS PART USES STRING MODEL
            //var selamlama = saat > 12 ? "İyi Günler":"Günaydın";
            //View(model: selamlama);

            //THIS PART USES ViewBag
            //ViewBag.Selamlama = saat > 12 ? "İyi Günler":"Günaydın";
            //ViewBag.UserName = "Hasan";

            //THIS PART USES ViewData
            ViewData["Selamlama"] = saat > 12 ? "İyi Günler":"Günaydın";
            //ViewData["UserName"] = "Hasan";

            int UserCount = Repository.Users.Where(info=>info.WillAttend == true).Count();

            var meetingInfo = new MeetingInfo()
            {
                Id = 1,
                Location = "İstanbul, ABC Kongre Merkezi",
                Date = new DateTime(2024,01,20,20,0,0),
                NumberOfPeople = UserCount
            };


            return View(meetingInfo);
        
        }
    }
}

MeetingApp/Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {
    
        [HttpGet]
        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model)
        {
            // database (not in this project)
            // list
            if(ModelState.IsValid){
            Repository.CreateUser(model);
            ViewBag.UserCount = Repository.Users.Where(info=>info.WillAttend == true).Count();
            return View("Thanks", model);
            }else{
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult List()  
        {
            return View(Repository.Users);
        }

        //meeting/details/1
        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }
        
    }
}

MeetingApp/Views/Home/Index.cshtml
@model MeetingInfo
<!--When you don't want to use the generic layout-->
@{
    ViewBag.Title = "Toplantı Başvuru";
    Layout = "_Layout2";
}
<main class="text-center">

    <h1 class="h4">@ViewData["Selamlama"]</h1>
    <p>Toplantı Katılım Durumunuzu Bildiriniz</p>
    <div class="card my-2">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">@Model.Location</li>
            <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") Tarihinde Gerçekleşecek</li>
            <li class="list-group-item">Katılan Kişi Sayısı : @Model.NumberOfPeople</li>
        </ul>
    </div>
    <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvuru Yap</a>
</main>

MeetingApp/Views/Meeting/Apply.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Formu";  
}
<h1 class="h4 text-center">Toplantı Katılım Formu</h1>
<form method="post" action="/meeting/apply" novalidate>    
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Attend State</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Select</option>
            <option value="true">Yes, Will Attend</option>
            <option value="false">No, Will Not Attend</option>
        </select>
    </div>

    <button class="btn btn-outline-primary" type="submit">Kaydet</button>
</form>

MeetingApp/Views/Meeting/Details.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Detayı";
}

@{
    var className = @Model.WillAttend == true ? "primary":"danger";
}

<main class="text-center">
    <h1 class="h4">Başvuru Detayı</h1>
        <p>
            <span class="badge text-bg-@className">
                @if(Model.WillAttend == true){
                    <text>Katılıyor</text>
                }else{
                    <text>Katılmıyor</text>
                }
            </span>
        </p>
        <p>Name: @Model.Name</p>
        <p>Email: @Model.Email</p>
        <p>Telefon: @Model.Phone</p>
        <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katılımcı Listesi</a>
    
</main>

MeetingApp/Views/Meeting/List.cshtml
@model List<UserInfo>
@{
    ViewBag.Title = "Toplantı Katılım Listesi";
}
<main class="text-center">
    <h1 class="h4">Toplantıya Katılım Listesi</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Ad</td>
                <td>Katılım Durumu</td>
                <td></td>
            </tr>
        </thead>
        <tbody>

            @{int i = 0; }

            @foreach(var user in Model){

                var durum = user.WillAttend == true ? "Yes":"No";
                var className = user.WillAttend == true ? "table-success" : "table-danger";
            
                @if(user.WillAttend == true) {
                    i++;
                }

                <tr class="@className">
                    <td>@user.Name</td>
                    <td>@durum</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="card">
        <div class="card-body">
            <span>Katılımcı Sayısı: @i</span>
        </div>
    </div>
</main>

MeetingApp/Views/Meeting/Thanks.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Özeti";
}
<main class="text-center">
    <h1 class="h4">Başvuru Özeti</h1>

    @if(Model.WillAttend == true)
    {
        <p>Teşekkürler @Model.Name, Toplantıya sizinle birlikte @ViewBag.UserCount kişi katılıyor.</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>
    } else
    {
        <p>@Model.Name, Katılmadığından dolay üzgünüz.</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru formu</a>
    }




</main>

MeetingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/css/styles.css"/>
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-primary text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

MeetingApp/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    <title>@ViewBag.Title - MeetingApp </title>
</head>
<body>
    <div class="bg-danger text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>